blank_issues_enabled: false
contact_links: 
  - name: 💬 Ask a question or Get Help.
    url: https://forum.access-hive.org.au/t/access-help-and-support/908
    about: For questions or support, please post on the ACCESS-Hive Forum instead!
    