name: New Event
description: Suggest new event to add to events page
title: "[New Event]: "
labels: ["New Event",]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for sharing your Workshop or Event with the ACCESS community.

        If there is a new event you would like listed in the [ACCESS-Hive Docs events section](https://docs.access-hive.org.au/events/) please include the following information:
  - type: input
    id: title
    attributes:
      label: Event title
      description: "The title of the Workshop or Event"
      placeholder: "e.g. Community Modelling Workshop"
    validations:
      required: true
  - type: input
    id: start
    attributes:
      label: Start date
      description: "Please provide the date your event starts"
      placeholder: "DD/MM/YYYY"
    validations:
      required: true
  - type: input
    id: end
    attributes:
      label: End date
      description: "Please provide the date your event finishes"
      placeholder: "DD/MM/YYYY"
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Location
      description: Where is the event taking place (can be virtual)?
      placeholder: "e.g. Parliament House, Canberra, ACT"
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Website
      description: Website URL for more information
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Description of your event. Include enough information to be 
        useful to potential attendees, but note it will be truncated to 
        255 characters when displayed.