name: Automatic merge

on:
  schedule: 
    # Run every day at 01:09 (AEST)
    # AEST is UTC+10 --> 01:09 AEST is 15:09 UTC
    - cron: "9 15 * * *"
  workflow_dispatch:

jobs:
#   check-links:
#     uses: ./.github/workflows/check_links.yml

  auto-merge:
    runs-on: ubuntu-latest
    # needs: check-links
    steps:
    - name: Checkout repo
      uses: actions/checkout@master
      with:
        ref: main
        fetch-depth: 0
        token: ${{ secrets.REPO_CONTENT_WRITE_TOKEN }}
    
    - name: Import GPG settings
      uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4  # v6.1.0
      with:
        gpg_private_key: ${{ secrets.GH_ACTIONS_BOT_GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GH_ACTIONS_BOT_GPG_PASSPHRASE }}
        git_config_global: true
        git_committer_name: ${{ vars.GH_ACTIONS_BOT_GIT_USER_NAME }}
        git_committer_email: ${{ vars.GH_ACTIONS_BOT_GIT_USER_EMAIL }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_tag_gpgsign: true
    
    - name: Merge development to main
      run: |
        git config --list
        git merge --no-ff -X theirs origin/development -m "Automatically merge 'development' to 'main'.
        Merge commit issued by the automatic_merge workflow."
        git push origin main
