name: Check links

on: 
#   pull_request: #Action fires anytime a PR is (re)opened or synchronized
#     types:
#       - opened
#       - reopened
#       - synchronize
#   workflow_call:
    workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main repo
      if: ${{github.event_name == 'pull_request'}}
      uses: actions/checkout@master

    - name: Checkout repo
      if: ${{github.event_name != 'pull_request'}}
      uses: actions/checkout@master
      with:
        ref: main
    
    - name: Link checker
      uses: lycheeverse/lychee-action@f81112d0d2814ded911bd23e3beaa9dda9093915 #v2.1.0
      with:
        fail: true
        args: --config .github/workflows/lychee-config.toml './docs/**/*.md' './docs/**/*.html'
