# =========== IMPORTANT!! READ THIS!! ============ #
# This file is used to check links and can be copied to be used in other websites.
# This workflow is triggered within RTD build by the `.readthedocs/scripts/check_links.sh` 
# script in the ACCESS-NRI/ACCESS-Hive-Docs repo.
# ============================================== #

name: Check links

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
        type: string
        description: "The GitHub repository in the form OWNER/REPO for which to check links."
      ref:
        required: true
        type: string
        description: "The repo ref (branch name or commit sha) for which to check links."
      mkdocs_yaml:
        type: string
        required: true
        description: "Path to the mkdocs.yml configuration file."
      lychee_config:
        type: string
        required: true
        description: "Path to the lychee configuration file."
      python_requirements_txt:
        type: string
        required: true
        description: "Path to the python requirements.txt file."

jobs:
  check-links:
    uses: access-nri/access-hive-docs/.github/workflows/check_links_workflow.yml@main
    with:
      mkdocs_yaml: "mkdocs.yml"  # MODIFY IF NEEDED: Path to your mkdocs.yml file
      python_requirements_txt: "requirements.txt"  # MODIFY IF NEEDED: Path to your python requirements.txt file.
    #   lychee_config: ".github/workflows/lychee_config.toml"  # MODIFY IF NEEDED: Path to your lychee configuration file. If omitted the default one from Hive Docs will be used.