name: Check links

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check-links:
    uses: access-nri/documentation-infra/.github/workflows/check_links_workflow.yml@v1
    with:
      repo: '${{ github.repository }}'
      ref_name: "${{ github.event_name == 'pull_request' && format('refs/pull/{0}/head', github.event.pull_request.number) || github.ref_name }}"
      rtd_project: 'access-hive-docs'
      python_requirements_txt: 'requirements.txt'
      mkdocs_yaml: 'mkdocs.yml'