# Reusable workflow to check for broken links in the documentation using lychee link checker
# (https://github.com/lycheeverse/lychee)

name: Check links workflow

on: 
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
        description: "The GitHub repository in the form OWNER/REPO for which to check links."
      ref:
        required: true
        type: string
        description: "The repo ref (branch name or commit sha) for which to check links."
      mkdocs_yaml:
        type: string
        required: true
        description: "Path to the mkdocs.yml configuration file."
      lychee_config:
        type: string
        required: true
        description: "Path to the lychee configuration file. If not provided, the default ACCESS-Hive-Docs one will be used."
      python_requirements_txt:
        type: string
        required: true
        description: "Path to the python requirements.txt file."
      base_url:
        type: string
        required: false
        description: "Base URL for the documentation."
    secrets:
      repo_read_token:
        required: false
        description: "Token with read permissions. Needed for private repositories."

env:
  DEFAULT_LYCHEE_CONFIG: access-nri/access-hive-docs/main/.github/workflows/lychee_config.toml
  DEFAULT_MKDOCS_CONFIG: mkdocs.yml
  DEFAULT_REQUIREMENTS_TXT: requirements.txt
  BUILD_FOLDER: ${{ github.workspace }}/docs_folder

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.ref }}
          token: ${{ secrets.repo_pat || github.token }}

      # If lychee_config is not provided, use the lychee_config.toml in this repo
      - name: Get lychee config
        id: get-lychee-config
        run: |
          if [ -n '${{ inputs.lychee_config }}' ]; then
            echo "Using provided lychee config: ${{ inputs.lychee_config }}"
            echo "lychee_config_path=${{ inputs.lychee_config }}" >> $GITHUB_OUTPUT
          else
            lychee_config_path="${{ github.workspace }}/lychee_config.toml"
            curl -sSL https://raw.githubusercontent.com/${{ env.DEFAULT_LYCHEE_CONFIG }} \
              -o "$lychee_config_path"
            echo "Lychee config not provided. Using default lychee config from Hive Docs repo:"
            echo "============= LYCHEE CONFIG ============="
            cat $lychee_config_path
            echo "========================================="
            echo "lychee_config_path=$lychee_config_path" >> $GITHUB_OUTPUT
          fi

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.x
          
      - name: Install dependencies
        run: |
          pip install -r ${{ inputs.python_requirements_txt || env.DEFAULT_REQUIREMENTS_TXT }}
      
      - name: Build mkdocs site
        run: |
          if [ -n '${{ inputs.base_url }}' ] ; then
            export REATHEDOCS_CANONICAL_URL='${{ inputs.base_url }}'
          fi
          mkdocs build --config-file ${{ inputs.mkdocs_yaml || env.DEFAULT_MKDOCS_CONFIG }} -d ${{ env.BUILD_FOLDER }}
        
      - name: Check links with lychee
        id: lychee
        uses: lycheeverse/lychee-action@a8c4c7cb88f0c7386610c35eb25108e448569cb0 #v2.7.0
        with:
          fail: true
          failIfEmpty: true
          args: --config ${{ steps.get-lychee-config.outputs.lychee_config_path }} '${{ env.BUILD_FOLDER }}/**/*.html'
