name: Delete PR preview comment
on:
  workflow_call
jobs:
  # Delete PR preview comment
  delete-pr-preview-comment:
    name: Delete PR preview comment
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Remove PR preview comment
        uses: access-nri/actions/.github/actions/comment@main
        with:
          delete: true
          label: ${{ vars.PR_PREVIEW_COMMENT_LABEL }}