# Configuration file for lychee link-checker (https://github.com/lycheeverse/lychee/blob/master/lychee.example.toml)

# Exclude URLs and mail addresses from checking (supports regex).
exclude = [
    '^https://code\.metoffice\.gov\.uk',
    '^https://web\.archive\.org/web/',
    '^http://127\.0\.0\.1:8000',
    '^https://www.linkedin.com/',
    '^https://www.freepik.com/',
    '%7B%7B', # Exclude jinja templating links that have double opening curly brackets in it
    '^https://www.freepik.com/',
    '^https://www.lanl.gov/',
]

# Exclude these filesystem paths from getting checked.
exclude_path = [
    "./docs/fontello",
    "./docs/fontawesome*",
]

# Set verbose level
verbose = "info"

# Don't show interactive progress bar while checking links.
no_progress = true

# Enable link caching. This can be helpful to avoid checking the same links on
# multiple runs.
cache = true

# Discard all cached requests older than this duration.
max_cache_age = "1d"

# Base URL or website root directory to check relative URLs.
base = "https://docs.access-hive.org.au/"

# Check links inside `<code>` and `<pre>` blocks as well as Markdown code
# blocks.
include_verbatim = true

# Check mail addresses
include_mail = false

